### ISSUE TITLE
Unable to import component: cannot import name 'get_random_bytes' from 'Crypto.Random' (unknown location)

### ISSUE THREAD

**Issue by HamsenBender** [peaceduck/remootio#14]
Remootio integration not loading since update to 2025.12.1 

Logger: homeassistant.setup
Source: setup.py:343
First occurred: 08:57:46 (1 occurrence)
Last logged: 08:57:46

Setup failed for custom integration 'remootio': Unable to import component: cannot import name 'get_random_bytes' from 'Crypto.Random' (unknown location)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1018, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1078, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1027, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/remootio/__init__.py", line 6, in <module>
    from aioremootio import ConnectionOptions, RemootioClient
  File "/usr/local/lib/python3.13/site-packages/aioremootio/__init__.py", line 15, in <module>
    from .remootioclient import \
        RemootioClient
  File "/usr/local/lib/python3.13/site-packages/aioremootio/remootioclient.py", line 26, in <module>
    from Crypto.Hash import HMAC, SHA256
  File "/usr/local/lib/python3.13/site-packages/Crypto/Hash/HMAC.py", line 39, in <module>
    from Crypto.Hash import BLAKE2s
  File "/usr/local/lib/python3.13/site-packages/Crypto/Hash/BLAKE2s.py", line 35, in <module>
    from Crypto.Random import get_random_bytes
ImportError: cannot import name 'get_random_bytes' from 'Crypto.Random' (unknown location)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 343, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1038, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1030, in async_get_component
    comp = self._get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1078, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1027, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/remootio/__init__.py", line 6, in <module>
    from aioremootio import ConnectionOptions, RemootioClient
  File "/usr/local/lib/python3.13/site-packages/aioremootio/__init__.py", line 15, in <module>
    from .remootioclient import \
        RemootioClient
  File "/usr/local/lib/python3.13/site-packages/aioremootio/remootioclient.py", line 26, in <module>
    from Crypto.Hash import HMAC, SHA256
  File "/usr/local/lib/python3.13/site-packages/Crypto/Hash/HMAC.py", line 39, in <module>
    from Crypto.Hash import BLAKE2s
  File "/usr/local/lib/python3.13/site-packages/Crypto/Hash/BLAKE2s.py", line 35, in <module>
    from Crypto.Random import get_random_bytes
ImportError: cannot import name 'get_random_bytes' from 'Crypto.Random' (unknown location)

**Comment by peaceduck** [comment]
Thanks. That is annoying. I am a bit behind on my updates. I will try to take a look at this and fix it tomorrow.

**Comment by HamsenBender** [comment]
@peaceduck seems like something different was going on with my installation, had the same error with another integration. Upgraded again to 2025.12.1 and now works without issues, so dunno what was wrong first time.
